🏝islands:
  - frontend/islands
🍚types:
  - frontend/types
💿libs:
  - frontend/libs
🧩components:
  - frontend/components
  - frontend/layouts
👗satic:
  - frontend/static
🏠localInfra:
  - docker-compose.yml
  - infra/dev/*
🐙github:
  - .github/*
✈ci:
  - .github/workflows/*
  - .github/labeler.yml
📄docs:
  - README.md
  - LICENSE
