🏝islands:
  - frontend/islands/*
🧩types:
  - frontend/types/*
💿usecases:
  - frontend/usecases/*
🗃components:
  - frontend/components/*
🖼layout:
  - frontend/layout/*
👗static:
  - frontend/static/*
🏠localInfra:
  - docker-compose.yml
  - infra/dev/*
🐙github:
  - .github/*
✈ci:
  - .github/workflows/*
  - .github/labeler.yml
📄docs:
  - README.md
  - LICENSE
