version: "3"
services:
  deno:
    build:
      context: .
      dockerfile: ./infra/dev/deno/Dockerfile
    volumes:
      - ./frontend:/frontend
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 7002:8000
