version: "3"
services:
  deno:
    build:
      context: .
      dockerfile: ./infra/deno/Dockerfile
    volumes:
      - ./portal:/frontend
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 8000:8000

  nginx:
    build: ./infra/nginx
    ports:
      - "80:80"
    depends_on:
      - "deno"
